// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChooseOperationController from "./choose_operation_controller"
application.register("choose-operation", ChooseOperationController)

import ChooseTypeController from "./choose_type_controller"
application.register("choose-type", ChooseTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import MapController from "./map_controller"
application.register("map", MapController)

import SingleMapController from "./single_map_controller"
application.register("single-map", SingleMapController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import UpdateFormController from "./update_form_controller"
application.register("update-form", UpdateFormController)
